workflows:
  ios-simulator:
    name: iOS Simulator Build
    environment:
      flutter: 3.24.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Setup and Build
        script: |
          echo "=== SETUP START ==="
          flutter --version
          flutter clean
          flutter pub get
          
          echo "=== iOS SETUP ==="
          cd ios
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 12.0/IPHONEOS_DEPLOYMENT_TARGET = 14.0/g' Runner.xcodeproj/project.pbxproj
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 13.0/IPHONEOS_DEPLOYMENT_TARGET = 14.0/g' Runner.xcodeproj/project.pbxproj
          sed -i '' 's/platform :ios, '\''12.0'\''/platform :ios, '\''14.0'\''/g' Podfile
          sed -i '' 's/platform :ios, '\''13.0'\''/platform :ios, '\''14.0'\''/g' Podfile
          sed -i '' 's/<string>12.0<\/string>/<string>14.0<\/string>/g' Flutter/AppFrameworkInfo.plist
          sed -i '' 's/<string>13.0<\/string>/<string>14.0<\/string>/g' Flutter/AppFrameworkInfo.plist
          pod install
          cd ..
          
          echo "=== SIMULATOR BUILD START ==="
          flutter build ios --debug --simulator --verbose
          echo "=== BUILD COMPLETE ==="
          
          echo "=== VERIFY OUTPUT ==="
          ls -la build/ios/iphonesimulator/
    artifacts:
      - build/ios/iphonesimulator/Runner.app
    publishing:
      email:
        recipients:
          - void7775@gmail.com
