name: Build iOS Simulator App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Cache pub
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Flutter env
        run: |
          flutter --version
          flutter doctor -v
          flutter precache --ios

      - name: Install dependencies
        run: flutter pub get
      
      - name: Cache Pods
        uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: Xcode diagnostics
        run: |
          xcodebuild -version
          xcodebuild -showsdks
          xcrun simctl list devices
          xcodebuild -list -workspace ios/Runner.xcworkspace || true

      - name: Cache DerivedData
        uses: actions/cache@v4
        with:
          path: build/DerivedData
          key: ${{ runner.os }}-dd-${{ hashFiles('ios/Podfile.lock', 'pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-dd-

      - name: Build with Xcode for Simulator (specific device)
        run: |
          set -euo pipefail
          mkdir -p build
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath build/DerivedData \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO build | tee build/xcodebuild.log

      - name: List build outputs
        if: always()
        run: |
          ls -la build || true
          ls -la build/DerivedData/Build/Products || true
          ls -la build/DerivedData/Build/Products/Debug-iphonesimulator || true

      - name: Upload Xcode logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-logs
          path: |
            build/xcodebuild.log
            build/DerivedData/Logs/Build/**

      - name: Upload app artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: build/DerivedData/Build/Products/Debug-iphonesimulator/Runner.app
