name: Build iOS Simulator App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: Flutter env
        run: |
          flutter --version
          flutter doctor -v
          flutter precache --ios

      - name: Install dependencies
        run: flutter pub get
      
      - name: Install CocoaPods
        run: |
          cd ios
          pod repo update
          pod install

      - name: Xcode diagnostics
        run: |
          xcodebuild -version
          xcodebuild -showsdks
          xcrun simctl list devices
          xcodebuild -list -workspace ios/Runner.xcworkspace || true

      - name: Select simulator destination
        id: select_sim
        run: |
          set -euo pipefail
          # Try preferred devices in order and pick first available UDID
          pick_udid() {
            xcrun simctl list devices available | awk -F'[()]' -v pat="$1" '$0 ~ pat {print $2; exit 0}'
          }
          UDID="$(pick_udid "iPhone 16 Pro ")"
          if [[ -z "$UDID" ]]; then UDID="$(pick_udid "iPhone 16 Pro Max ")"; fi
          if [[ -z "$UDID" ]]; then UDID="$(pick_udid "iPhone 16 ")"; fi
          if [[ -z "$UDID" ]]; then UDID="$(pick_udid "iPhone SE \(3rd generation\)")"; fi
          if [[ -z "$UDID" ]]; then
            echo "No matching simulator found" >&2
            xcrun simctl list devices available
            exit 1
          fi
          echo "Chosen UDID: $UDID"
          echo "udid=$UDID" >> $GITHUB_OUTPUT

      - name: Build with Xcode for Simulator (specific device)
        run: |
          set -euo pipefail
          mkdir -p build
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination "id=${{ steps.select_sim.outputs.udid }}" \
            -derivedDataPath build/DerivedData \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO build | tee build/xcodebuild.log

      - name: List build outputs
        if: always()
        run: |
          ls -la build || true
          ls -la build/DerivedData/Build/Products || true
          ls -la build/DerivedData/Build/Products/Debug-iphonesimulator || true

      - name: Upload Xcode logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-logs
          path: |
            build/xcodebuild.log
            build/DerivedData/Logs/Build/**

      - name: Upload app artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: build/DerivedData/Build/Products/Debug-iphonesimulator/Runner.app
